### ISSUE TITLE
RES obs_info_file error

### ISSUE THREAD

**Issue by pjuckem** [PESTools/pestools#51]
I get an error when using pestools.Res without an obs_info_file.  I had cloned the Barr repo of pestools, but uninstalled it (pip uninstall pestools), cloned the github repo, and installed that one, but still same problem.  It runs fine if the obs_info_file for the CC model is supplied.  Here are a couple of screen shots:
![image](https://cloud.githubusercontent.com/assets/3900764/8293462/2afea0ae-18fb-11e5-9095-0899283b2ccf.png)
![image](https://cloud.githubusercontent.com/assets/3900764/8293483/42043f70-18fb-11e5-8e5b-a42b25303ef3.png)
.
.
.
![image](https://cloud.githubusercontent.com/assets/3900764/8293500/57d96258-18fb-11e5-96cb-2ebf5925764c.png)

**Comment by mnfienen** [comment]
On my Mac I found a different error (just pull-requested a fix....it was minor) but then the code causing Paul trouble worked fine for me

**Comment by pjuckem** [comment]
It's probably just me....though I'm not sure what's been corrupted on my
system.  Will look into it more & try on my laptop which has Anaconda
instead of Enthought...
Paul

**Comment by echristi** [comment]
I'm able to reproduce Paul's issue.  Haven't had a chance to dig into why.

I didn't see Mike's pull request.

**Comment by mnfienen** [comment]
I see Andy fixed the bug I was going to pull request about. I was working on an old fork which now I updated. Still can't reproduce Paul's error though...

**Comment by echristi** [comment]
I hadn't updated since Andy made changes either.  Once I did that and re-ran setup.py I no longer get the error Paul was getting.

**Comment by pjuckem** [comment]
ARG! 
Thanks for the gentle reminder on setup.py.  I had checked "git log" to ensure Andy's fix had been pulled, but hopefully this will burn "git pull",  then "python setup.py install" into my memory!  All is well on both windows machines.  Thanks.  I'll close this issue.
